spring:
  datasource:
    # Local development - Audit user
    username: audit_user
    password: ${AUDIT_DB_PASSWORD:AuditService789!}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

  cloud:
    vault:
      enabled: false

  jpa:
    show-sql: true

logging:
  level:
    com.udea.bancodigital: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
